### ISSUE TITLE
The same "ota-user-profile: System error" issue with advancedtelematic / ota-community-edition

### ISSUE THREAD

**Issue by jinlingyi** [uptane/ota-community-edition#1]
reference to:
https://github.com/advancedtelematic/ota-community-edition/issues/105#issue-689132326

**Comment by simao** [comment]
You can try the `webapp` branch here, it uses a patched version of ota-plus-web

But like I said, the webapp is not supported here. You should use only the api.

**Comment by jinlingyi** [comment]
The webapp branch in this repo, the app of uptane/ota-plus-web:06053862900a6be6e9b54fe4529e4d1070c98711 can't start of this error:
```kubectl logs app-5fcc54c4b5-cn8sj
Oops, cannot start the server.
java.lang.ClassNotFoundException: com.advancedtelematic.auth.garage.NoLoginAction
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.advancedtelematic.auth.oidc.OidcModule.bindToClass$1(OidcModule.scala:13)
	at com.advancedtelematic.auth.oidc.OidcModule.bindings(OidcModule.scala:17)
	at play.api.inject.guice.GuiceableModuleConversions.guice(GuiceInjectorBuilder.scala:339)
	at play.api.inject.guice.GuiceableModuleConversions.guice$(GuiceInjectorBuilder.scala:338)
	at play.api.inject.guice.GuiceableModule$.guice(GuiceInjectorBuilder.scala:273)
	at play.api.inject.guice.GuiceableModuleConversions$$anon$3.$anonfun$guiced$2(GuiceInjectorBuilder.scala:318)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at play.api.inject.guice.GuiceableModuleConversions$$anon$3.guiced(GuiceInjectorBuilder.scala:318)
	at play.api.inject.guice.GuiceableModule$.$anonfun$guiced$1(GuiceInjectorBuilder.scala:295)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.immutable.List.flatMap(List.scala:352)
	at play.api.inject.guice.GuiceableModule$.guiced(GuiceInjectorBuilder.scala:295)
	at play.api.inject.guice.GuiceBuilder.createModule(GuiceInjectorBuilder.scala:170)
	at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:109)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

**Comment by simao** [comment]
Added a commit that on this branch should fix this error. I'm afraid using the webapp is going to be trial and error like this... :\
